image: registry.gitlab.com/termoshtt/accel/ubuntu18.04-cuda10.2:master

stages:
  - docker
  - test
  - deploy

cache:
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo-check:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/accel; cargo check
    - cd $CI_PROJECT_DIR/accel-core; cargo check
    - cd $CI_PROJECT_DIR/accel-derive; cargo check

test:accel-derive:
  stage: test
  script:
    - cd accel-derive
    - cargo test

.with_gpu:
  before_script:
    - nvidia-smi
  tags:
    - gpu
  only:
    - master
    - tags
    - /^gpu\/.*/

test:accel:
  extends: .with_gpu
  stage: test
  script:
    - cd accel
    - cargo test

test:ignored:
  extends: .with_gpu
  stage: test
  script:
    - cd accel
    - cargo test -- --ignored
  allow_failure: true

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir -p public
    - cargo doc --no-deps --document-private-items
    - mv target/doc public/accel
    - cd accel-core
    - cargo doc
    - mv ./target/nvptx64-nvidia-cuda/doc ../public/accel-core
  artifacts:
    paths:
      - public
  # only:
  #   - master

.build:
  image: docker:stable
  stage: docker
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C docker ${TAG}
  only:
    refs:
      - master
      - tags
    changes:
      - docker/*

include: '/docker/ci.yml'
